version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/indp-server
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 180
      runas: ubuntu
