spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:server-secrets/application-local.yml

---

spring:
  config:
    activate:
      on-profile: dev
    import:
      - classpath:server-secrets/application-dev.yml

---

spring:
  config:
    activate:
      on-profile: prod1
    import:
      - classpath:server-secrets/application-prod-default.yml
      - classpath:server-secrets/application-prod1.yml

---

spring:
  config:
    activate:
      on-profile: prod2
    import:
      - classpath:server-secrets/application-prod-default.yml
      - classpath:server-secrets/application-prod2.yml
