= Indp Application API Document

:doctype: book
:source-highlighter: highlightjs
:sectlinks:
:toc: left
:toclevels: 3

== 매장 (Store)

=== 매장 목록 조회 (간단 정보)

operation::store-controller-test/find-simple-stores[snippets='http-request,query-parameters']
operation::store-controller-test/find-simple-stores[snippets='http-response,response-fields']

=== 매장 목록 조회

operation::store-controller-test/find-stores[snippets='http-request,query-parameters']
operation::store-controller-test/find-stores[snippets='http-response,response-fields']

== 지역 (Region)

=== 지역 목록 조회

operation::region-controller-test/find-regions[snippets='http-request']
operation::region-controller-test/find-regions[snippets='http-response']


== 음악 추천 (Recommendation)

=== 음악 추천하기

operation::recommendation-controller-test/register-recommendation[snippets='http-request,request-fields']
operation::recommendation-controller-test/register-recommendation[snippets='http-response,response-headers']

== 문의 (Contact)

=== 문의하기

operation::contact-controller-test/register-contact[snippets='http-request,request-fields']
operation::contact-controller-test/register-contact[snippets='http-response,response-headers']
