= Indp Application API Document
:doctype: book
:source-highlighter: highlightjs
:sectlinks:
:toc: left
:toclevels: 3

== 매장 (Store)

=== 매장 목록 조회 (간단 정보)

==== Request

operation::store-controller-test/find-simple-stores[snippets='http-request,query-parameters']

==== Response

operation::store-controller-test/find-simple-stores[snippets='http-response,response-fields']

=== 매장 목록 조회

==== Request

operation::store-controller-test/find-stores[snippets='http-request,query-parameters']

==== Response

operation::store-controller-test/find-stores[snippets='http-response,response-fields']

== 음악 추천 (Recommendation)

=== 음악 추천하기

==== Request

operation::recommendation-controller-test/register-recommendation[snippets='http-request,request-fields']

==== Response

operation::recommendation-controller-test/register-recommendation[snippets='http-response,response-headers']

== 문의 (Contact)

=== 문의하기

==== Request

operation::contact-controller-test/register-contact[snippets='http-request,request-fields']

==== Response

operation::contact-controller-test/register-contact[snippets='http-response,response-headers']